import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import LanguageSelect from '@/components/LanguageSelect';
import axios from "axios";

export default function Home() {
  const [language, setLanguage] = useState<string | null>(null);
  const [text, setText] = useState("");
  const [result, setResult] = useState("");
  return (
    <>
      <Head>
        <title>Language Translation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={{textAlign: "center"}}>Language Translation</h1>
        <span style={{display: "block", marginBottom: "2rem"}} />

        <div style={{width: "200px", marginBottom: "1rem"}}>
          <LanguageSelect language={language} setLanguage={setLanguage} />
        </div>
        <textarea
          className={styles.textEntry}
          value={text}
          placeholder="Enter some text to translate to conversational form"
          onChange={e => setText(e.target.value)}
          rows={8}
          cols={80}
        />

        <button
          style={{display: "block"}}
          className={styles.translateButton}
          onClick={() => {
            axios.post("/api/translate", {
              language: language,
              text: text,
            }).then((r) => {
              console.log(r);
              setResult(r.data.result.trim());
            }).catch((e) => {
              console.log(e);
            });
          }}
        >
          Translate
        </button>

        <textarea
          className={styles.result}
          readOnly
          value={result}
          rows={8}
          cols={80}
        />

      </main>
    </>
  )
}
